from . import base
from . import product_product
from . import product_template
from . import res_partner
from . import resource_booking
from . import resource_booking_combination
from . import resource_booking_type
from . import resource_resource
from . import sale_order
from . import sale_order_line
from . import team_m
from . import team_m_model
from . import team_m_param
from . import resource_calendar
from . import resource_calendar_attendance
