from . import base
from . import event_event
from . import event_registration
from . import product_attribute
from . import product_attribute_value
from . import product_product
from . import product_template
from . import product_template_attribute_line
from . import res_partner
from . import resource_booking
from . import resource_booking_combination
from . import resource_booking_type
from . import resource_booking_type_combination_rel
from . import resource_calendar
from . import resource_calendar_attendance
from . import resource_group
from . import resource_resource
from . import sale_order
from . import sale_order_line
from . import teamm
from . import teamm_alias
from . import teamm_model
from . import teamm_param
